security:
  oauth2:
    client:
      client-id: micro-inner
      client-secret: micro
      scope: all
      release-urls:
        - /v2/api-docs
        - /api/**
        - /user/sendVerifyCode/*
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/micro?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true

  redis:
    database: 1
    host: localhost
    port: 6379

#    阿里云短信服务
aliyun:
  sms:
    accessKeyId: xxx
    accessKeySecret: xxx
    signName: xxx
    verificationCode: xxx
    endpoint: xxx
#    mybatis输出日志
mybatis-plus:
 configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

base:
  tenant:
    tables:
      - sys_role
      - sys_role_menu
      - sys_user_role
